
import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 16

[window]
dimensions = { columns = 150, lines = 60 }
