
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Light" }
size = 14

[window]
dimensions = { columns = 150, lines = 60 }
