
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Light" }
size = 14

[window]
dimensions = { columns = 150, lines = 60 }
