theme = "base16_transparent"
# theme = "catppuccin_mocha"
# theme = "github_dark"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
auto-save = true
color-modes = true
cursorline = true
completion-trigger-len = 1

[editor.file-picker]
# hidden = false
ignore = true
git-ignore=false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
